apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: inventory-db
  description: Inventory service database
  tags:
    - mongodb
    - database
spec:
  type: database
  lifecycle: experimental
  owner: group:guests
  system: inventory-app